FROM tomcat:9.0-jdk11-openjdk-slim

# Remove default Tomcat apps
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy the WAR file generated by Maven to Tomcat's webapps directory as ROOT.war
COPY target/corporate-website.war /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080
